name: Cypress Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 1 * * 1"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.12.2

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm install

      - name: Test
        run: pnpm run test:ci
