name: Cypress Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 1 * * 1"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.12.2

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      # Install cypress's binary under custom directory to cache
      - name: Set Cypress path (non-windows)
        run: echo "CYPRESS_CACHE_FOLDER=$HOME/.cache/Cypress" >> $GITHUB_ENV

      - name: Cache Cypress's binary
        uses: actions/cache@v3
        with:
          key: cypress-bin-v1
          path: ${{ env.CYPRESS_CACHE_FOLDER }}

      - name: Install Cypress
        run: pnpm exec cypress install

      - name: Test
        run: pnpm run test:ci
